import {
  Entity,
  model,
  property
} from '@loopback/repository';
import {User} from './user.model';

@model({
  settings: {
    foreignKeys: {
      fk_commission_userId: {
        name: 'fk_commissions_userId',
        entity: 'user',
        entityKey: 'id',
        foreignKey: 'userId',
      },
      fk_commission_contestId: {
        name: 'fk_commissions_contestId',
        entity: 'contest',
        entityKey: 'id',
        foreignKey: 'contestId',
      },
    },
  }
})
export class Commission extends Entity {
  @property({
    description: 'commission\'s record id, generated by postgreSQL, can be changed to loopback or postgreSQL uuid generator or custom',
    type: 'number',
    id: true,
    generated: true,
    postgresql: {
      columnName: 'id',
      dataType: 'integer',
      dataLength: null,
      dataPrecision: null,
      dataScale: 0,
      nullable: 'NO',
      unique: true,
    },
  })
  id: number;

  //no neet to be defined, it's already done in contest
  @property({
    postgresql: {
      columnName: 'contest_id'
    }
  })
  contestId: number;

  //no neet to be defined, it's already done in user
  @property({
    postgresql: {
      columnName: 'user_id'
    }
  })
  userId: number;

  constructor(data?: Partial<Commission>) {
    super(data);
  }
}

export interface CommissionRelations {
  user: User
}

export type CommissionsWithRelations = Commission & CommissionRelations;
