import {
  Entity,
  model,
  property
} from '@loopback/repository';

// https://loopback.io/doc/en/lb4/Model.html
// https://loopback.io/doc/en/lb4/Model.html#data-mapping-properties
@model()
export class Contest extends Entity {
  @property({
    description: 'contest\'s id, generated by postgreSQL, can be changed to loopback or postgreSQL uuid generator or custom',
    type: 'number',
    id: true,
    generated: true,
    postgresql: {
      columnName: 'id',
      dataType: 'integer',
      dataLength: null,
      dataPrecision: null,
      dataScale: 0,
      nullable: 'NO',
      unique: true,
    },
  })
  id: number;

  @property({
    description: 'contest\'s title, can be changed',
    type: 'string',
    id: false,
    required: true,
    postgresql: {
      columnName: 'display_name',
      dataType: 'text',
      dataLength: null,
      dataPrecision: null,
      dataScale: null,
      nullable: 'NO',

    },
  })
  title: string;

  //DATES
  //https://www.postgresql.org/docs/9.1/datatype-datetime.html
  //Conversion
  //https://loopback.io/doc/en/lb4/PostgreSQL-connector.html

  @property({
    type: 'date',
    description: 'Timestamp with timezone when was contest created',
    //setting up to time of creation automatically
    defaultFn: 'now',
    postgresql: {
      columnName: 'created_at',
      dataType: 'timestamp with time zone',
    },
  })
  createdAt: Date;

  @property({
    type: 'date',
    description: 'Timestamp with timezone when was contest updated',
    //setting up to time of creation automatically
    defaultFn: 'now',
    postgresql: {
      columnName: 'updated_at',
      dataType: 'timestamp with time zone',
    },
  })
  updatedAt: Date;

  @property({
    type: 'date',
    description: 'Timestamp with timezone when was contest created',
    //needed at the time of creation
    required: true,
    postgresql: {
      columnName: 'starting_at',
      dataType: 'timestamp with time zone',
    },
  })
  startDate: Date;

  @property({
    type: 'date',
    description: 'Timestamp with timezone when was contest created',
    //needed at the time of creation
    required: true,
    defaultFn: 'now',
    postgresql: {
      columnName: 'ending_at',
      dataType: 'timestamp with time zone',
    },
  })
  endDate: Date;

  constructor(data?: Partial<Contest>) {
    super(data);
  }
}

export interface ContestRelations {
}

export type ContestWithRelations = Contest & ContestRelations;
