import {
  Entity,
  model,
  property
} from '@loopback/repository';

@model({
  settings: {
    foreignKeys: {
      fk_mark_solutionIdc: {
        name: 'fk_mark_solutionIdc',
        entity: 'solution',
        entityKey: 'id',
        foreignKey: 'solutionId',
      },
      fk_mark_userId: {
        name: 'fk_mark_userId',
        entity: 'user',
        entityKey: 'id',
        foreignKey: 'userId',
      },
    },
  }
})
export class Mark extends Entity {
  @property({
    description: 'mark\'s record id, generated by postgreSQL, can be changed to loopback or postgreSQL uuid generator or custom',
    type: 'number',
    id: true,
    generated: true,
    postgresql: {
      columnName: 'id',
      dataType: 'integer',
      dataLength: null,
      dataPrecision: null,
      dataScale: 0,
      nullable: 'NO',
      unique: true,
    },
  })
  id: number;

  //no neet to be defined, it's already done in solution
  @property({
    postgresql: {
      columnName: 'solution_id'
    }
  })
  solutionId: number;

  //no neet to be defined, it's already done in user
  @property({
    postgresql: {
      columnName: 'user_id'
    }
  })
  userId: number;

  @property({
    description: 'mark\'s comment',
    type: 'string',
    id: false,
    required: true,
    postgresql: {
      columnName: 'mark_comment',
      datatype: 'character varying',
      dataLength: 250,
      nullable: 'NO',
    },
  })
  comment: string;

  @property({
    description: 'mark\'s value',
    type: 'number',
    id: false,
    required: true,
    postgresql: {
      columnName: 'mark_value',
      dataType: 'integer',
      dataLength: null,
      dataPrecision: null,
      dataScale: null,
      nullable: 'NO',
    },
  })
  value: 0 | 2 | 5 | 6;

  constructor(data?: Partial<Mark>) {
    super(data);
  }
}

export interface MarkRelations {
}

export type MarkWithRelations = Mark & MarkRelations;
