import {
  belongsTo,
  Entity,
  model,
  property
} from '@loopback/repository';
import {Mark} from '.';
import {Task, TaskWithRelations} from './task.model';
import {User, UserWithRelations} from './user.model';

@model()
export class Solution extends Entity {
  @property({
    description: 'solution\'s record id, generated by postgreSQL, can be changed to loopback or postgreSQL uuid generator or custom',
    type: 'number',
    id: true,
    generated: true,
    postgresql: {
      columnName: 'id',
      dataType: 'integer',
      dataLength: null,
      dataPrecision: null,
      dataScale: 0,
      nullable: 'NO',
      unique: true,
    },
  })
  id: number;

  //no neet to be defined, it's already done in contest
  @belongsTo(() => Task)
  taskId: number;

  //no neet to be defined, it's already done in user
  @belongsTo(() => User)
  userId: number;

  //no neet to be defined, it's already done in mark
  @belongsTo(() => Mark)
  markId: number;

  @property({
    description: 'solution\'s text',
    type: 'string',
    id: false,
    required: true,
    postgresql: {
      columnName: 'solution_text',
      datatype: 'character varying',
      dataLength: 2000,
      nullable: 'NO',
    },
  })
  text: string;

  constructor(data?: Partial<Solution>) {
    super(data);
  }
}

export interface SolutionRelations {
  task: TaskWithRelations;
  user: UserWithRelations;
}

export type SolutionWithRelations = Solution & SolutionRelations;
