import {
  belongsTo,
  Entity,
  model,
  property
} from '@loopback/repository';
import {Contest, ContestWithRelations} from './contest.model';

@model()
export class Task extends Entity {
  @property({
    description: 'task\'s record id, generated by postgreSQL, can be changed to loopback or postgreSQL uuid generator or custom',
    type: 'number',
    id: true,
    generated: true,
    postgresql: {
      columnName: 'id',
      dataType: 'integer',
      dataLength: null,
      dataPrecision: null,
      dataScale: 0,
      nullable: 'NO',
      unique: true,
    },
  })
  id: number;

  //no neet to be defined, it's already done in contest
  @belongsTo(() => Contest)
  contestId: number;

  //no neet to be defined, it's already done in user
  @property({
    description: 'task\'s text',
    type: 'string',
    id: false,
    required: true,
    postgresql: {
      columnName: 'task_text',
      datatype: 'character varying',
      dataLength: 2000,
      nullable: 'NO',
    },
  })
  text: string;

  constructor(data?: Partial<Task>) {
    super(data);
  }
}

export interface TaskRelations {
  contest: ContestWithRelations;
}

export type TaskWithRelations = Task & TaskRelations;
