import {
  Entity,
  model,
  property
} from '@loopback/repository';

@model({
  settings: {
    foreignKeys: {
      fk_task_contestId: {
        name: 'fk_task_contestId',
        entity: 'contest',
        entityKey: 'id',
        foreignKey: 'contestId',
      },
    },
  }
})
export class Task extends Entity {
  @property({
    description: 'task\'s record id, generated by postgreSQL, can be changed to loopback or postgreSQL uuid generator or custom',
    type: 'number',
    id: true,
    generated: true,
    postgresql: {
      columnName: 'id',
      dataType: 'integer',
      dataLength: null,
      dataPrecision: null,
      dataScale: 0,
      nullable: 'NO',
      unique: true,
    },
  })
  id: number;

  //no neet to be defined, it's already done in contest
  @property({
    postgresql: {
      columnName: 'contest_id'
    }
  })
  contestId: number;

  //no neet to be defined, it's already done in user
  @property({
    description: 'task\'s text',
    type: 'string',
    id: false,
    required: true,
    postgresql: {
      columnName: 'task_text',
      datatype: 'character varying',
      dataLength: 2000,
      nullable: 'NO',
    },
  })
  text: string;

  constructor(data?: Partial<Task>) {
    super(data);
  }
}

export interface TaskRelations {
}

export type TaskWithRelations = Task & TaskRelations;
